### ISSUE TITLE
repo install local

### ISSUE THREAD

**Issue by azcoigreach** [pumpkin-py/pumpkin-py#306]
There is no repo command to install a local repo directory that was manually cloned or created locally.  The current repo install and command requires a URL.

I am working with private gits and pulling my repos manually.  I have to tear down my Docker containers and rebuild to get the requirements.txt to build.  There is no mechanism to do that from inside Pumpkin.py.

**Comment by sinus-x** [comment]
'repo install' clones a repository into `modules/` directory. You can create or symlink a repository into that directory, and after resetarting, the bot will pick them up.

Alternatively, you can pull private gits by specifying SSH URI instead of HTTPS one. I assume you'd have to copy or mirror system `.ssh/` directory into your container for that.

**Comment by azcoigreach** [comment]
I figured out to **clone** and **update** a **PRIVATE** github.

Add your USERNAME:PASSWORD to the github.com URL
`https://<USERNAME>:<PASSWORD>@github.com/some-user/some-repo.git`

If you have two-factor enabled.  It will be necessary to generate a PERSONAL ACCESS TOKEN for your github account.
